server:
  port: 8888
spring:
  application:
    name: config-server
  security:
    basic:
      enabled: false
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pedroapalma/service-config
          skipSslValidation: true
          timeout: 10
          username: ${GIT_USER}
          password: ${GIT_PASS}